#!/bin/sh
bspc rule -r "*"

###--Autostart--###
killall "nm-applet"
nmapplet &
killall "picom"
picom -b &
pgrep -x sxhkd > /dev/null || sxhkd &
xfce4-terminal &

###--Monitors--###
bspc monitor eDP -d 1 2 3 4 5 6 7
bspc monitor HDMI-1-0 -d 8 9 0

###--Global Settings--##
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

###--Colour Scheme--###
bspc config normal_border_color "##44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

###--Monitor and Desktop Settings--###
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10
